In [1]:
import numpy as np 
import matplotlib.pyplot as plt
import transformation as tr


In [109]:
a = np.array([[1,2,3], [4,5,6], [7,8,9]])
b = np.array([[3,3,3], [4,5,6], [7,8,9]])

lst = [a, a, b, b, b, b ,b, b, b, a ]

def print_matrix_mul(transformation_list, result=None):
    transformation_list.reverse()
    row0 = [matrix[0] for matrix in transformation_list]
    row1 = [matrix[1] for matrix in transformation_list]
    row2 = [matrix[2] for matrix in transformation_list]

    result0 = "" if result is None else f"     |{result[0]}|"
    result1 = "" if result is None else f"  =  |{result[1]}|"
    result2 = "" if result is None else f"     |{result[2]}|"

    row0_str = [str(row) for row in row0]

    row0_str = "|" +"|   |".join(row0_str) + "|" + f"{result0}"+  "\n"
    row1_str = [str(row) for row in row1]
    row1_str = "|" +"| x |".join(row1_str) + "|" + f"{result1}"+  "\n"
    

    row2_str = [str(row) for row in row2]
    row2_str = "|" +"|   |".join(row2_str) + "|" + f"{result2}"+  "\n"

    return row0_str + row1_str + row2_str


mul = print_matrix_mul(lst, a)
print(mul)

|[1 2 3]|   |[3 3 3]|   |[3 3 3]|   |[3 3 3]|   |[3 3 3]|   |[3 3 3]|   |[3 3 3]|   |[3 3 3]|   |[1 2 3]|   |[1 2 3]|     |[1 2 3]|
|[4 5 6]| x |[4 5 6]| x |[4 5 6]| x |[4 5 6]| x |[4 5 6]| x |[4 5 6]| x |[4 5 6]| x |[4 5 6]| x |[4 5 6]| x |[4 5 6]|  =  |[4 5 6]|
|[7 8 9]|   |[7 8 9]|   |[7 8 9]|   |[7 8 9]|   |[7 8 9]|   |[7 8 9]|   |[7 8 9]|   |[7 8 9]|   |[7 8 9]|   |[7 8 9]|     |[7 8 9]|



In [73]:

def plot_polyg(polygon_list, size=(5,5), num=0):
    colors = ['red', 'blue', 'black', 'green', 'brown', 'yellow']
    f = plt.figure(num, figsize=size)
    plt.grid()
    plt.axhline(0, color='black')
    plt.axvline(0, color='black')

    polygon_list = np.array(polygon_list)
    xlim = 5
    ylim = 5
    
    plt.xlim([-xlim, xlim + 1])
    plt.ylim([-xlim, xlim + 1])

    plt.xticks(np.arange(-xlim, xlim, 1))
    plt.yticks(np.arange(-ylim, ylim, 1))
    for polygon, color in zip(polygon_list, colors):
        t = plt.Polygon(polygon.T, color=color)
        plt.gca().add_patch(t)

    return f



In [14]:
points = np.array([[0, 0], [1, 0], [0, 1]]).T
final = np.array([[0, 3], [2, 3], [0,5]]).T

lst =[1, 2]
lst.pop()


lst

[1]

In [16]:
H = tr.compute_transformation(final, points)
newH = np.round(H, decimals=3)

newH

array([[ 2., -0.,  0.],
       [-0.,  2.,  3.],
       [-0., -0.,  1.]])

In [15]:
transformed = tr.apply_transformation([newH], points=points)
f = plot_polyg([points, final, ])
plt.show()